/**
 * Public-API snapshot gate (zero dependencies, Deno-native).
 *
 * Renders the public API surface — signatures *and* JSDoc — of every published
 * entrypoint via `deno doc`, strips volatile source locations, and either
 * writes the golden snapshot (`--write`) or fails if the current surface has
 * drifted from it (`--check`).
 *
 * The snapshot is the frozen contract described in `AGENTS.md` §3: any change to
 * it is a deliberate, human-reviewed event, recorded in `CHANGELOG.md`.
 *
 *   deno run -A scripts/api-snapshot.ts --check   # CI: fail on drift
 *   deno run -A scripts/api-snapshot.ts --write   # re-baseline deliberately
 *
 * @module
 */

/** The published entrypoints whose surface is frozen, in snapshot order. */
const ENTRYPOINTS = [
  "src/index.ts",
  "src/wire/index.ts",
  "src/testing/index.ts",
  "src/testing/harness.ts",
] as const;

/** Where the golden snapshot lives, relative to this package root. */
const SNAPSHOT_PATH = "api/dns-sd-shared.api.md";

/** Render one entrypoint's public surface as location-free `deno doc` text. */
async function renderEntrypoint(entry: string): Promise<string> {
  const cmd = new Deno.Command(Deno.execPath(), {
    args: ["doc", entry],
    env: { NO_COLOR: "1" },
    stdout: "piped",
    stderr: "piped",
  });
  const { success, stdout, stderr } = await cmd.output();
  if (!success) {
    throw new Error(
      `deno doc failed for ${entry}:\n${new TextDecoder().decode(stderr)}`,
    );
  }
  const text = new TextDecoder().decode(stdout);
  // Drop volatile `Defined in file://…:line:col` locations, then collapse the
  // blank lines they leave behind so the snapshot is stable across edits.
  const body = text
    .split("\n")
    .filter((line) => !line.startsWith("Defined in "))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd();
  return body;
}

/** Build the full snapshot document across all entrypoints. */
async function buildSnapshot(): Promise<string> {
  const parts = [
    "# Public API snapshot — @momics/dns-sd-shared",
    "",
    "> Generated by `scripts/api-snapshot.ts`. Do not edit by hand.",
    "> This is the frozen public surface (see `AGENTS.md` §3). Regenerate with",
    "> `deno task snapshot:api` only for a deliberate, reviewed API change.",
    "",
  ];
  for (const entry of ENTRYPOINTS) {
    parts.push(`## ${entry}`, "", await renderEntrypoint(entry), "");
  }
  return parts.join("\n").trimEnd() + "\n";
}

function fail(message: string): never {
  console.error(message);
  Deno.exit(1);
}

const mode = Deno.args.includes("--check")
  ? "check"
  : Deno.args.includes("--write")
  ? "write"
  : fail("usage: api-snapshot.ts (--check | --write)");

const snapshot = await buildSnapshot();

if (mode === "write") {
  await Deno.writeTextFile(SNAPSHOT_PATH, snapshot);
  console.log(`Wrote API snapshot → ${SNAPSHOT_PATH}`);
} else {
  let existing: string;
  try {
    existing = await Deno.readTextFile(SNAPSHOT_PATH);
  } catch {
    fail(
      `No API snapshot at ${SNAPSHOT_PATH}. Run \`deno task snapshot:api\` first.`,
    );
  }
  if (existing !== snapshot) {
    fail(
      [
        "Public API surface has changed — it no longer matches the frozen",
        `snapshot at ${SNAPSHOT_PATH}.`,
        "",
        "This is a STOP SIGN (AGENTS.md §3). If the change was NOT intended,",
        "revert it. If it WAS deliberate, re-baseline and record it in the",
        "changelog:",
        "",
        "  deno task snapshot:api",
        "  # then add a CHANGELOG.md entry",
      ].join("\n"),
    );
  }
  console.log("Public API surface matches the frozen snapshot.");
}
